services:
  niffler-all-db:
    container_name: niffler-all
    image: postgres:15.1
    environment:
      - CREATE_DATABASES=niffler-auth,niffler-currency,niffler-spend,niffler-userdata
      - PGUSER=postgres
      - POSTGRES_PASSWORD=secret
      - TZ=GMT+3
      - PGTZ=GMT+3
    volumes:
      - ./postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "max_prepared_transactions=100" ]
    networks:
      - niffler-network
   
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - niffler-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - niffler-network

volumes:
  pgdata:

networks:
  niffler-network:
    driver: bridge